apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflowsystem-worker
  namespace: workflowsystem
  labels:
    app: workflowsystem-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: workflowsystem-worker
  template:
    metadata:
      labels:
        app: workflowsystem-worker
    spec:
      containers:
      - name: workflowsystem-worker
        image: workflowsystem-worker:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: workflowsystem-db-secret
              key: connection-string
        - name: ConnectionStrings__ReadOnlyConnection
          valueFrom:
            secretKeyRef:
              name: workflowsystem-db-secret
              key: readonly-connection-string
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: workflowsystem-redis-secret
              key: connection-string
        - name: HorizontalScaling__WorkerCount
          value: "5"
        - name: HorizontalScaling__QueueTimeout
          value: "00:05:00"
        - name: HorizontalScaling__RetryAttempts
          value: "3"
        - name: Kubernetes__PodName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: Kubernetes__Namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: workflowsystem-worker-service
  namespace: workflowsystem
spec:
  selector:
    app: workflowsystem-worker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP 